### ISSUE TITLE
PBFT catch up: update the current leader

### ISSUE THREAD

**Issue by nkcr** [dedis/dela#214]
**This is a big issue that makes the system unusable if nodes restart.**

## Context

The leader rotation works in a round-robin fashion. Starting from node at index 0, each view change will assign the next node as the new leader, following a simple `(i+1) mod n` formula, where `i` is the current leader index and `n` the total number of nodes.

Every node maintains its local index of the current leader. A node will accept a view change only if the new proposed leader corresponds to *its* next expected leader. It also checks that blocks proposals come from *its* current leader.

## Problem

This leader index `i` starts at `0` when a node starts, and is not updated in case a node is behind the chain and does a catch up. This is a problem, as the leader may have changed without the catching up node knowing about that. The catching up node will then have an outdated current leader index `i = 0` and reject every block proposals.

Even worse, if the catching up node is node `0`, this node will think that it is the leader node, and send block proposals to all other nodes.

## How to reproduce

Use the scripts that are yet on the `manual_tests` branch:

```sh
cd test
./teststart.sh
# send a first transaction, everything fine
./testlist.sh 1 -1
# => kill node 0
# => use ctrl-B + arrows to navigate to the window
./testlist.sh 2 2
# Now node 1 is the leader, everything fine
# => restart node 0
./testlist.sh 2 3
# node 0 thinks he is the leader, he is sending proposals
```

### Update sync block

Update the sync block mechanism to include the current leader. This would mean that the catching up node is trusting the remote node that sends the catch up message to send the correct current leader.

Pros:

- Only touches the blockcync part

Cons:

- Partially solves the problem, as a bad node could send a wrong leader index

### Update the blocks content

Update blocks content to include the leader. This would allow the catching up node to check who is the leader in the last block, and update its current leader accordingly.

Pros:

- This is the most explicit way of solving this issue
- Adds interesting information to the block

Cons:

- Increases the size of blocks
- Having the leader in a block is not very relevant
- Feels like the simple and dirty solution

### Update the consensus mechanism

Even if a node doubts about the current leader, it should be convinced to update its current leader if a threshold of nodes came to a consensus on a block. This could be done in the `Finalize` step, when the block is committed. This would probably require to update the PBFT state machine to store the "rejected leader" in the prepare step, but then accept it if the Finalize step succeeds.

Note that this doesn't solve the problem in case nodes are performing a view change. Therefore, nodes should store view change proposals, and accept one once it has a threshold of proposals for a same node. Right now any proposals that does not concern the next expected leader is rejected.

Pros:

- Only touches the PBFT state machine
- Ensures a node always has a correct leader index
- Requires minimal changes

Cons:

- Adds a new state to the PBFT state machine

**Comment by ineiti** [comment]
FWIW: the cothority/byzcoin implementation used the roster stored in the block to indicate the leader: the first node in the roster list is the leader.

When a node started, even if it was the leader, it first caught up all blocks. Then it used the roster in the last block to check if its the leader or not.

**Comment by nkcr** [comment]
# Introduction

This is a more detailed explanation of the solution. I choose the last option "Update the consensus mechanism". It mainly evolves around the principle of **leader skepticism**. A node will reject a block proposal from an unexpected leader, but keep the right to later accept this leader if the block comes to be accepted.

# Explanation

Suppose nodes A, B, C, and D, with B as the current accepted leader.

1) C restarts. It now assumes that A is the leader, because this the default value when a node starts
2) C receives a block proposal from B, but rejects it. However, it saves B as a skeptical candidate. It also saves the block ID as the `tentativeRound`. (in the PBFT state machine, a roundID corresponds to the current block's hash proposal)
3) A, C, and D will agree on committing the block, and finalize it.
4) Once the block finalized, C will receive a catchup message with the block. If the block hash is equal to the `tentativeRound`, then C accepts B as the new leader.

# Limitations

A node could try to fool another node into thinking this is the leader. For that to work, the adversary node must:

1. Send a `Prepare` message to the victim, making the victim save the adversary node as the skeptical candidate
2. Prevent the victim from receiving the right `Prepare` message from the leader, but let it receive the catchup
3. When the victim receives the catchup message, it will save the adversarial node as its leader
4. Do 2) and 3) for every new block proposal, otherwise the victim will go back to the right leader

For this adversarial scenario to work, a valid catchup block is necessary. Thus, a `2f + 1` threshold of honest node must remain, which prevents any adversarial from taking the leadership position with a majority. Let's say that `f` nodes are victimized and convinced about a wrong leader. Convincing another node will require to make this new node not participating into the block creation, which make the total of participating node equal to `2f`, which is not enough to create a new block. Therefore, not any new node can be fooled.

**Comment by ineiti** [comment]
Hmm - after reading this, I think the `Update the blocks content` is still my favorite:

- there is no way that any outside node can interfere with the leader proposal 
- it is always clear who the current leader is, even if all nodes restart

But I think I'm missing some information as to how you can have `with B as the current accepted leader`. How and why is B currently accepted?

This might also be a good time to go back to the papers :) In cothority/byzcoin I implemented a partial ByzcoinX protocol. Partial, because there was only 1 shard. If you look at Section V-A in the [Omniledger paper](https://eprint.iacr.org/2017/406.pdf), you get a short description. From what I understand, the `shard policy file` has all the information about who is the leader. And I suppose that this `shard policy file` must result from a consensus. This is why I suppose that it is a good idea to put the leader in the block.

Happy to discuss if you think it helps.

**Comment by nkcr** [comment]
> But I think I'm missing some information as to how you can have with B as the current accepted leader. How and why is B currently accepted?

Each node has an in-memory state, in which they keep track of what they think is the current leader. As such, if all nodes were to restart, they would all naturally select node 0 as the leader and things would run normally. A node will update its current leader once it receives a threshold of view change messages for its next expected leader.

In Dela, blocks are super light, which aims to make the blockchain as efficient as possible. This is why the roster is not included (but we include a "ChangeSet" of the roster, if the roster changed from the previous block). Including the roster just for the sake of knowing the leader is overkill in this case.

**Comment by ineiti** [comment]
OK, there is a lot going on then... Do you have some documentation about these decisions? My first questions would be:

- do you still use the skipchain structure?
- do you need to go through all blocks then to know the current roster?
- why don't you just include the ID of the current leader in the block?

**Comment by ineiti** [comment]
Is there a possibility to implement Narwhal/Tusk? Here is a nice blog post about it:

https://decentralizedthoughts.github.io/2022-06-28-DAG-meets-BFT/

And they have a rust implementation that should show all the details.

**Comment by nkcr** [comment]
> Is there a possibility to implement Narwhal/Tusk?

Sure, you can implement your own [ordering module](https://github.com/dedis/dela/tree/master/core/ordering) with your favorite consensus algorithm. If you want to supervise a semester project, be our guest :) (I proposed one to implement Hotstuff, but it sadly didn't went through..)

**Comment by ineiti** [comment]
So Narwhal/Tusk has it's own way to handle the mempool between the nodes. Also, it uses a DAG instead of linearly connected blocks.

Does that mean that you could write a mempool module, a DAG module, and a consensus module relying on these two?

**Comment by nkcr** [comment]
> Does that mean that you could write a mempool module, a DAG module, and a consensus module relying on these two?

yes! And then you add on the top the existing modules provided by Dela, such as the network overlay (mino), execution and validation (smart contract), store (db), and txn (transaction).

**Comment by ineiti** [comment]
Sounds like a good idea for a semester-project then! If I find the time, I'll propose it to Bryan and look if there is some student who's interested in it.
